name: Cloud Concierge
 
on:
  push:
    branches:
      - master
 
jobs:
  run-cloud-concierge:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
 
      - name: Run cloud-concierge
        run: docker run --env-file ./my-env-file.env -v ${{ github.workspace }}:/main -v ${{ secrets.AWS_CREDENTIALS }}:/main/credentials/aws:ro -w /main dragondropcloud/cloud-concierge:latest
 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update cloud state
          branch: cloud-concierge-results
          title: Cloud Concierge Results
          body: This PR contains the latest cloud state and codified resources.