name: Run cloud-concierge

on:
  push:
    branches:
      - master

jobs:
  run-cloud-concierge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pull cloud-concierge image
      run: docker pull dragondropcloud/cloud-concierge:latest

    - name: Run cloud-concierge
      run: |
        docker run --env-file ./my-env-file.env \
          -v ${{ github.workspace }}:/main \
          -v $HOME/.aws:/main/credentials/aws:ro \
          -w /main \
          dragondropcloud/cloud-concierge:latest
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Add State of Cloud report"
        branch: cloud-concierge-report
        title: "State of Cloud Report"
        body: "This PR contains the latest State of Cloud report generated by cloud-concierge."
